CREATE DATABASE QLBH
ON PRIMARY
	(NAME = QLBH_data1,
	FILENAME = 'D:\HK1(2023-2024)\HeCoSoDuLieu\ThucHanh\Week1\Bai2\QLBH_Data.mdf',
	SIZE = 10MB, MAXSIZE = 40MB, FILEGROWTH = 1MB)
LOG ON
	(NAME = QLBH_Log,
	FILENAME = 'D:\HK1(2023-2024)\HeCoSoDuLieu\ThucHanh\Week1\Bai2\QLBH_Log.ldf',
	SIZE = 6MB, MAXSIZE = 8MB, FILEGROWTH = 1MB)