CREATE DATABASE QLSV
ON PRIMARY
	(NAME = QLSV_Data, 
	FILENAME = 'D:\HK1(2023-2024)\HeCoSoDuLieu\ThucHanh\Week1\ViDu\QLSV_Data.mdf',
	SIZE = 10MB, MAXSIZE = 15MB, FILEGROWTH = 20%)
LOG ON 
	(NAME = QLSV_Log,
	FILENAME = 'D:\HK1(2023-2024)\HeCoSoDuLieu\ThucHanh\Week1\ViDu\QLSV_Log.ldf',
	SIZE = 3MB, MAXSIZE = 5MB, FILEGROWTH = 1MB)
