CREATE DATABASE QLSach 
ON PRIMARY (NAME = QLSach_data,
	FILENAME = 'D:\HK1(2023-2024)\HeCoSoDuLieu\ThucHanh\Week1\Bai1\QLSach_Data.mdf',
	SIZE = 20MB, MAXSIZE = 40MB, FILEGROWTH = 1MB)
LOG ON (NAME = QLSach_Log,
	FILENAME = 'D:\HK1(2023-2024)\HeCoSoDuLieu\ThucHanh\Week1\Bai1\QLSach_Log.ldf',
	SIZE = 6MB, MAXSIZE = 8MB, FILEGROWTH = 1MB)