--Pham Thanh Tri
--1.Tao CSDL
CREATE DATABASE QLBH
ON PRIMARY (NAME = 'QLBH_Data',
		FILENAME = 'D:\HK1(2023-2024)\HeCoSoDuLieu\ThucHanh\Week2\QLBH_Data.MDF',
		SIZE = 20MB, MAXSIZE = 40MB, FILEGROWTH = 1MB)
LOG ON 
	(NAME = 'QLBH_Log',
	FILENAME = 'D:\HK1(2023-2024)\HeCoSoDuLieu\ThucHanh\Week2\QLBH_Log.LDF',
	SIZE = 10MB, MAXSIZE = 20MB, FILEGROWTH = 1MB)

--2. Su dung DB

USE QLBH

--3. Tao Table co 1 vai rang buoc

CREATE TABLE NHOMSANPHAM
(	MaNhom INT NOT NULL,
	TenNhom NVARCHAR(15),
	PRIMARY KEY (MaNhom))

CREATE TABLE SANPHAM
(	MaSP INT NOT NULL,
	TenSP NVARCHAR(40) NOT NULL,
	MANCC INT,
	MoTa NVARCHAR(50),
	MaNhom INT,
	Donvitinh NVARCHAR(20),
	PRIMARY KEY (MaSP))

CREATE TABLE HOADON
(	MaHD INT NOT NULL,
	NgayLapHD DATETIME DEFAULT getdate(),
	NgayGiao DATETIME,
	NoiChuyen NVARCHAR(60) NOT NULL,
	MaKH CHAR(5),
	PRIMARY KEY (MaHD))

CREATE TABLE CT_HOADON
(	MaHD INT NOT NULL REFERENCES HOADON(MaHD),
	MaSP INT NOT NULL REFERENCES SANPHAM(MaSP),
	SoLuong SMALLINT,
	DonGia MONEY,
	ChietKhau MONEY,
	PRIMARY KEY (MaHD, MaSP))

CREATE TABLE NHACUNGCAP
(	MaNCC INT NOT NULL,
	TenNCC NVARCHAR(40) NOT NULL,
	DiaChi NVARCHAR(60),
	Phone NVARCHAR(24),
	SoFax NVARCHAR(24),
	DCMail NVARCHAR(50),
	PRIMARY KEY (MaNCC))

CREATE TABLE KHACHHANG
(	MaKH CHAR(5) NOT NULL,
	TenKH NVARCHAR(40) NOT NULL,
	LoaiKH NVARCHAR(3),
	DiaChi NVARCHAR(60),
	Phone NVARCHAR(24),
	DCMail NVARCHAR(50),
	DiemTL INT,
	PRIMARY KEY (MaKH))

--4. Them cac rang buoc cho cac bang

--4.a Bang SANPHAM
ALTER TABLE SANPHAM
	ADD FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC)

ALTER TABLE SANPHAM
	ADD FOREIGN KEY (MaNhom) REFERENCES NHOMSANPHAM(MaNhom)

ALTER TABLE SANPHAM 
	ADD GiaGoc MONEY, SLTon MONEY

ALTER TABLE SANPHAM
	ADD CONSTRAINT GiaGoc CHECK (GiaGoc > 0), CONSTRAINT SLTon CHECK (SLTon >= 0)

--4.b Bang HOADON
ALTER TABLE HOADON
	ADD CONSTRAINT NgayLapHD CHECK (NgayLapHD >= Getdate())

ALTER TABLE HOADON
	ADD FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)

ALTER TABLE HOADON
	ADD LoaiHD CHAR(1) DEFAULT 'N'

ALTER TABLE HOADON
	ADD CONSTRAINT LoaiHD CHECK (LoaiHD = 'N' OR LoaiHD = 'X' OR LoaiHD = 'C' OR LoaiHD = 'T')

ALTER TABLE HOADON
	ADD CONSTRAINT NgayGiao CHECK (NgayGiao >= NgayLapHD)

--4.c Bang CT_HOADON
ALTER TABLE CT_HOADON
	ADD CONSTRAINT SoLuong CHECK (SoLuong > 0), CONSTRAINT ChietKhau CHECK (ChietKhau >= 0)

--4.d Bang KHACHHANG
ALTER TABLE KHACHHANG
	ADD CONSTRAINT LoaiKH CHECK (LoaiKH = 'VIP' OR LoaiKH = 'TV' OR LoaiKH = 'VL')

ALTER TABLE KHACHHANG
	ADD CONSTRAINT DiemTL CHECK (DiemTL >= 0)
