USE [master]
GO

/****** Object:  Database [Movies]    Script Date: 9/28/2023 4:48:13 PM ******/
CREATE DATABASE [Movies]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Movies_data', FILENAME = N'D:\HK1(2023-2024)\HeCoSoDuLieu\ThucHanh\Week3\Movies_data.MDF' , SIZE = 25600KB , MAXSIZE = 40960KB , FILEGROWTH = 1024KB ),
( NAME = N'Movies_data2', FILENAME = N'D:\HK1(2023-2024)\HeCoSoDuLieu\ThucHanh\Week3\Movies_data2.NDF' , SIZE = 15360KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Movies_log', FILENAME = N'D:\HK1(2023-2024)\HeCoSoDuLieu\ThucHanh\Week3\Movies_log.LDF' , SIZE = 6144KB , MAXSIZE = 8192KB , FILEGROWTH = 1024KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Movies].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Movies] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Movies] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Movies] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Movies] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Movies] SET ARITHABORT OFF 
GO

ALTER DATABASE [Movies] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Movies] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [Movies] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Movies] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Movies] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Movies] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Movies] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Movies] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Movies] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Movies] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Movies] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Movies] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Movies] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Movies] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Movies] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Movies] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Movies] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Movies] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Movies] SET  MULTI_USER 
GO

ALTER DATABASE [Movies] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Movies] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Movies] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Movies] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Movies] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Movies] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Movies] SET QUERY_STORE = ON
GO

ALTER DATABASE [Movies] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Movies] SET  READ_WRITE 
GO


