CREATE DATABASE QlDuAn
ON PRIMARY
	(NAME = 'QlDuAn_data',
	FILENAME = 'T:\DL\QlDuAn_data.MDF',
	SIZE = 25, MAXSIZE = 40, FILEGROWTH = 1)
LOG ON
	(NAME = 'QlDuAn_log',
	FILENAME = 'T:\DL\QlDuAn_log.LDF',
	SIZE = 6, MAXSIZE = 8, FILEGROWTH = 1)

USE QlDuAn

CREATE TABLE DuAn
	(MaDA CHAR(5) PRIMARY KEY,
	TenDA NVARCHAR(30) NOT NULL)

CREATE TABLE CongViec
	(MaCV CHAR(5) PRIMARY KEY,
	TenCV NVARCHAR(30) NOT NULL)

CREATE TABLE NhanVien
	(MaNV CHAR(5) PRIMARY KEY,
	HoTen NVARCHAR(40) NOT NULL,
	Phai CHAR(3) CHECK (Phai IN ('Nam', 'Nu')),
	NgaySinh DATETIME,
	MaPB CHAR(5) NOT NULL,
	NhomTruong CHAR(5) REFERENCES NhanVien(MaNV))

CREATE TABLE PhongBan
	(MaPB CHAR(5) PRIMARY KEY,
	TenPB NVARCHAR(30),
	MaTruongPhuong CHAR(5) REFERENCES NhanVien(MaNV))

CREATE TABLE NhanVien_DuAn
	(MaDA CHAR(5) REFERENCES DuAn(MaDA),
	MaNV CHAR(5) REFERENCES NhanVien(MaNV),
	MaCV CHAR(5) REFERENCES CongViec(MaCV),
	ThoiGian INT NOT NULL CHECK (THoiGian > 0),
	PRIMARY KEY (MaDA, MaNV, MaCV))

ALTER TABLE NhanVien 
	ADD FOREIGN KEY (MaPB) REFERENCES PhongBan(MaPB)

