--Pham Thanh Tri - 22687551
--TUAN3: Tao bang co rang buoc
DROP DATABASE QLBH
CREATE DATABASE QLBH
ON PRIMARY
	(NAME = 'QLBH_Data',
	FILENAME = 'D:\HK1(2023-2024)\HeCoSoDuLieu\ThucHanh\Week3\QLBH_Data.MDF',
	SIZE = 20, MAXSIZE = 40, FILEGROWTH = 1)
LOG ON
	(NAME = 'QLBH_Log',
	FILENAME = 'D:\HK1(2023-2024)\HeCoSoDuLieu\ThucHanh\Week3\QLBH_Log.LDF',
	SIZE = 10, MAXSIZE = 20, FILEGROWTH = 1)

USE QLBH

CREATE TABLE NHOMSANPHAM
	(MaNhom INT PRIMARY KEY,
	TenNhom NVARCHAR(15))


CREATE TABLE NHACUNGCAP
	(MaNCC INT PRIMARY KEY,
	TenNCC NVARCHAR(40) NOT NULL,
	DiaChi NVARCHAR(60),
	Phone NVARCHAR(24),
	SoFax NVARCHAR(24),
	DCMail NVARCHAR(50))

CREATE TABLE KHACHHANG
	(MaKH CHAR(5) PRIMARY KEY,
	TenKH NVARCHAR(40) NOT NULL,
	LoaiKH NVARCHAR(3) CHECK(LoaiKH IN('VIP', 'TV', 'VL')),
	DiaChi NVARCHAR(60),
	Phone NVARCHAR(24),
	DCMail NVARCHAR(50),
	DiemTL INT CHECK(DiemTL >= 0))

CREATE TABLE HOADON
	(MaHD INT PRIMARY KEY,
	NgayLapHD DATETIME DEFAULT GETDATE() CHECK(NgayLapHD >= GETDATE()),
	NgayGiao DATETIME,
	NoiChuyen NVARCHAR(60) NOT NULL,
	MaKH CHAR(5) REFERENCES KHACHHANG(MaKH))

CREATE TABLE SANPHAM
	(MaSP INT PRIMARY KEY,
	TenSP NVARCHAR(40) NOT NULL,
	MaNCC INT REFERENCES NHACUNGCAP(MaNCC),
	MoTa NVARCHAR(50),
	MaNhom INT REFERENCES NHOMSANPHAM(MaNhom),
	DonViTinh NVARCHAR(20),
	GiaGoc MONEY CHECK(GiaGoc > 0),
	SLTON INT CHECK(SLTON >= 0))

CREATE TABLE CT_HoaDon
	(MaHD INT NOT NULL REFERENCES HOADON(MaHD),
	MaSP INT NOT NULL REFERENCES SANPHAM(MaSP),
	SoLuong SMALLINT CHECK(SoLuong > 0),
	DonGia MONEY,
	ChietKhau MONEY CHECK(ChietKhau >= 0),
	PRIMARY KEY(MaHD, MaSP))

ALTER TABLE HOADON
	ADD LoaiHD CHAR(1) DEFAULT 'N' CHECK(LoaiHD IN ('N', 'X', 'C', 'T'))

ALTER TABLE HOADON
	ADD CONSTRAINT NgayGiao CHECK(NgayGiao >= NgayLapHD)

